/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Base;

import java.awt.*;
import java.awt.geom.*;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author donih
 */
public class PieChartPanel extends javax.swing.JPanel {    
    String[] toko = {"PENDAPATAN", "PENGELUARAN"};      // Array untuk menyimpan nama kategori
    int[] persentase = new int[2];                      // Array untuk menyimpan persentase
    Color[] warna = {Color.GREEN, Color.RED};           // Array untuk menyimpan warna
    
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;         // Mengonversi objek Graphics menjadi Graphics2D
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);    // Mengaktifkan anti-aliasing agar gambar tdk burik
        this.setBackground(Color.WHITE);    // background
        float total = 0.0f;
        
        // Menghitung total persentase dari semua kategori
        for (int k = 0; k < persentase.length; k++) total += persentase[k];
        float sudut, awal = 90;
        
        // Inisialisasi variabel untuk menggambar diagram
        float lx = 250, ly = 70, lw = 10, lh = 10;
        for (int k = 0; k < persentase.length; k++) {
            sudut = 360.0f * persentase[k] / total;
            Shape sektor = new Arc2D.Float(70, 30, 150, 150, awal, sudut, Arc2D.PIE);
            g2.setColor(warna[k]);
            g2.fill(sektor);
            awal += sudut;
            g2.fill(new Rectangle2D.Float(lx, ly, lw, lh));
            g2.setColor(java.awt.Color.BLACK);
            g2.drawString(toko[k], lx + lw + 5, ly + lh);
            ly += (lh + 5);
            g2.setColor(Color.WHITE);   // lingkaran putih di tengah diagram
            g2.fillOval(125, 85, 40, 40);
        }
    }
        
    public PieChartPanel() {
        initComponents();
        try {
            // mengammmbil total penjualan dari database
            ResultSet resultSetPendapatan = konek.getConnection().createStatement().executeQuery
        ("SELECT SUM(total) AS total_penjualan FROM penjualan WHERE MONTH(tgl_penjualan) = MONTH(CURRENT_DATE()) "
                + "AND YEAR(tgl_penjualan) = YEAR(CURRENT_DATE());");
            if (resultSetPendapatan.next()) {   // Jika ada hasil, ambil total penjualan dan menyimpannya ke dalam array persentase indeks 0
                persentase[0] = resultSetPendapatan.getInt("total_penjualan");
            }
            
            // mengambil total pembelian dari database
            ResultSet resultSetPenjualan = konek.getConnection().createStatement().executeQuery
        ("SELECT SUM(total) AS total_pembelian FROM pembelian WHERE MONTH(tgl_pembelian) = MONTH(CURRENT_DATE()) "
                + "AND YEAR(tgl_pembelian) = YEAR(CURRENT_DATE());");
            if (resultSetPenjualan.next()) {    // Jika ada hasil, ambil total pembelian dan menyimpannya ke dalam array persentase indeks 1
                persentase[1] = resultSetPenjualan.getInt("total_pembelian");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
